### ISSUE TITLE
Final DCL Porject Submisson Code Checklist

### ISSUE THREAD

**Issue by mlederbauer** [mlederbauer/NMRcraft#43]
Do ths ~~25 May

Code (30%)
- [x] Formal criteria compliance: The code must meet all formal requirements specified in the report outline. final check @mlederbauer 
- [x] Documentation: An informative README file should be included, explaining the project's purpose, structure, and setup instructions. Let’s work on this together and add new documentation whenever we add a new feature @tiaguinho-code @strsamue @mlederbauer @kbiniek @wikicraft 
- [x] Readability and structure: The code should be readable and well-organized, facilitating easy navigation and understanding. Thanks to the pre-commit and code formatting tool gods but fnal check with `black -l 79 .` @mlederbauer 
- [x] Best coding practices: The code should generally follow the guidelines from PEP8 coding style as shown in the exercises, including appropriate documentation (docstrings and comments). Black can be used as a tool to format your code. See above
- [x] Execution: The code should be executable without errors and the teaching team (after possible consultation with the group members) should be able to run it. Let’s do a final check of the project in a brand new docker container to follow the installation instructions “by the book” – could you take care of this? @tiaguinho-code 
- [x] Performance: The code should execute within a reasonable timeframe and reproduce the presented results accurately. Let’s also do this in a final run @tiaguinho-code @mlederbauer

**Comment by tiaguinho-code** [comment]
Yes, I can def take care of the production container and see to it being super easy to use and if possible lightweight.
I will also look into some time eaters in the code and see if I can get it to be quicker.
